// <auto-generated />
using System;
using Comp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comp.Infrastructure.Migrations
{
    [DbContext(typeof(CompDbContext))]
    [Migration("20260914205708_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comp.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_occurred_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Year", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_year_name");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.EntrySession", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EventId")
                        .HasName("pk_entry_sessions");

                    b.ToTable("entry_sessions", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<bool>("CountsForStandings")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_for_standings");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<int>("EventNumber")
                        .HasColumnType("integer")
                        .HasColumnName("event_number");

                    b.Property<DateTimeOffset?>("FinalisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalised_at");

                    b.Property<Guid?>("FinalisedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalised_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("PenaltySeconds")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("penalty_seconds");

                    b.Property<int>("RunsPerShooter")
                        .HasColumnType("integer")
                        .HasColumnName("runs_per_shooter");

                    b.Property<int>("ScoringRulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_rules_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CompetitionId", "EventNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_events_competition_id_event_number");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int?>("PositionInSquad")
                        .HasColumnType("integer")
                        .HasColumnName("position_in_squad");

                    b.Property<Guid>("ShooterId")
                        .HasColumnType("uuid")
                        .HasColumnName("shooter_id");

                    b.Property<Guid?>("SquadId")
                        .HasColumnType("uuid")
                        .HasColumnName("squad_id");

                    b.HasKey("Id")
                        .HasName("pk_event_participants");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_event_participants_league_id");

                    b.HasIndex("ShooterId")
                        .HasDatabaseName("ix_event_participants_shooter_id");

                    b.HasIndex("SquadId")
                        .HasDatabaseName("ix_event_participants_squad_id");

                    b.HasIndex("EventId", "ShooterId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_participants_event_id_shooter_id");

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.EventResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("best_run_id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<int?>("EventTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("event_time_ms");

                    b.Property<Guid?>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("integer")
                        .HasColumnName("league_points");

                    b.Property<int?>("LeaguePosition")
                        .HasColumnType("integer")
                        .HasColumnName("league_position");

                    b.Property<int?>("OverallPosition")
                        .HasColumnType("integer")
                        .HasColumnName("overall_position");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rules_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_event_results");

                    b.HasIndex("BestRunId")
                        .HasDatabaseName("ix_event_results_best_run_id");

                    b.HasIndex("EventParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_results_event_participant_id");

                    b.HasIndex("LeagueId", "EventParticipantId")
                        .HasDatabaseName("ix_event_results_league_id_event_participant_id");

                    b.HasIndex("EventId", "LeagueId", "LeaguePosition")
                        .HasDatabaseName("ix_event_results_event_id_league_id_league_position");

                    b.ToTable("event_results", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AbsencesCountAsZero")
                        .HasColumnType("boolean")
                        .HasColumnName("absences_count_as_zero");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<int>("DropWorstCount")
                        .HasColumnType("integer")
                        .HasColumnName("drop_worst_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PointsDecrement")
                        .HasColumnType("integer")
                        .HasColumnName("points_decrement");

                    b.Property<int>("PointsForFirst")
                        .HasColumnType("integer")
                        .HasColumnName("points_for_first");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_leagues_competition_id_name");

                    b.HasIndex("CompetitionId", "Tier")
                        .IsUnique()
                        .HasDatabaseName("ix_leagues_competition_id_tier");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.LeagueMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<Guid>("ShooterId")
                        .HasColumnType("uuid")
                        .HasColumnName("shooter_id");

                    b.HasKey("Id")
                        .HasName("pk_league_memberships");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_league_memberships_league_id");

                    b.HasIndex("ShooterId")
                        .HasDatabaseName("ix_league_memberships_shooter_id");

                    b.HasIndex("CompetitionId", "ShooterId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_memberships_competition_id_shooter_id");

                    b.ToTable("league_memberships", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsDnf")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dnf");

                    b.Property<int>("PenaltyCount")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_count");

                    b.Property<int?>("RawTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("raw_time_ms");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<int>("RunNumber")
                        .HasColumnType("integer")
                        .HasColumnName("run_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_runs_idempotency_key");

                    b.HasIndex("EventParticipantId", "RunNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_runs_event_participant_id_run_number");

                    b.ToTable("runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_runs_dnf_has_no_time", "(is_dnf and raw_time_ms is null) or (not is_dnf and raw_time_ms is not null)");

                            t.HasCheckConstraint("ck_runs_penalty_count_non_negative", "penalty_count >= 0");

                            t.HasCheckConstraint("ck_runs_raw_time_ms_positive", "raw_time_ms is null or raw_time_ms > 0");
                        });
                });

            modelBuilder.Entity("Comp.Domain.Shooter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MembershipNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("membership_no");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("pk_shooters");

                    b.ToTable("shooters", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("integer")
                        .HasColumnName("squad_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_squads");

                    b.HasIndex("EventId", "SquadNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_squads_event_id_squad_number");

                    b.ToTable("squads", (string)null);
                });

            modelBuilder.Entity("Comp.Domain.EntrySession", b =>
                {
                    b.HasOne("Comp.Domain.Event", null)
                        .WithOne()
                        .HasForeignKey("Comp.Domain.EntrySession", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_sessions_events_event_id");
                });

            modelBuilder.Entity("Comp.Domain.Event", b =>
                {
                    b.HasOne("Comp.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_competitions_competition_id");
                });

            modelBuilder.Entity("Comp.Domain.EventParticipant", b =>
                {
                    b.HasOne("Comp.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_events_event_id");

                    b.HasOne("Comp.Domain.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_participants_leagues_league_id");

                    b.HasOne("Comp.Domain.Shooter", null)
                        .WithMany()
                        .HasForeignKey("ShooterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_shooters_shooter_id");

                    b.HasOne("Comp.Domain.Squad", null)
                        .WithMany()
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_participants_squads_squad_id");
                });

            modelBuilder.Entity("Comp.Domain.EventResult", b =>
                {
                    b.HasOne("Comp.Domain.Run", null)
                        .WithMany()
                        .HasForeignKey("BestRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_results_runs_best_run_id");

                    b.HasOne("Comp.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_results_events_event_id");

                    b.HasOne("Comp.Domain.EventParticipant", null)
                        .WithMany()
                        .HasForeignKey("EventParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_results_event_participants_event_participant_id");

                    b.HasOne("Comp.Domain.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_results_leagues_league_id");
                });

            modelBuilder.Entity("Comp.Domain.League", b =>
                {
                    b.HasOne("Comp.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_competitions_competition_id");
                });

            modelBuilder.Entity("Comp.Domain.LeagueMembership", b =>
                {
                    b.HasOne("Comp.Domain.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_memberships_competitions_competition_id");

                    b.HasOne("Comp.Domain.League", null)
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_memberships_leagues_league_id");

                    b.HasOne("Comp.Domain.Shooter", null)
                        .WithMany()
                        .HasForeignKey("ShooterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_memberships_shooters_shooter_id");
                });

            modelBuilder.Entity("Comp.Domain.Run", b =>
                {
                    b.HasOne("Comp.Domain.EventParticipant", null)
                        .WithMany()
                        .HasForeignKey("EventParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_runs_event_participants_event_participant_id");
                });

            modelBuilder.Entity("Comp.Domain.Squad", b =>
                {
                    b.HasOne("Comp.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_squads_events_event_id");
                });
#pragma warning restore 612, 618
        }
    }
}
